[app]
id = "booking-system.api"
enable = true
version = "1.0"
name = "booking system app"
developer = ["bico.steve4@gmail.com"]


[logger]
path = "./logs"
writer = "both"
file = "booking-system.log"
level = "debug"
handler = "json"


# local mysql 
[[mysql]]
name = "mysql"
host = "127.0.0.1"
port = 3306
username = ""
password = ""
schema = ""


# redis configs
[[redis]]
name = "redis"
address = ""
password = ""
port = ""
database = 0


[[kafka]]
name = 'kafka'
broker = ""
topic = ""
key = ""


[[http]]
name = "main"
host = "0.0.0.0"
port = 7001
adminport = 7002
path = "/api"
cors = { allowed_method = [
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "OPTIONS",
], allowed_header = [
  "Accept",
  "Accept-Language",
  "Content-Type",
  "Content-Language",
  "Origin",
], allowed_origin = [
  "*",
] }
args = { disableAuth = false }
contenttype = "application/json"


# secrets
[[secrets]]
name = "secrets"
jwt = ""
sendgrid = ""
mailfrom = ""
atklng = ""
appusername = ""


# Stripe
[[stripe]]
name = "stripe"
stripesecret = ""
publishable = ""
successURL = "http://host**/success"
cancelURL = "http://host**/cancel"
