basePath: /api
info:
  contact:
    email: bicosteve4@gmail.com
    name: Bico Oloo
    url: https://github.com/bicosteve
  description: Booking API to perform booking CRUD operations
  title: Booking API
  version: "1"
paths: {}
schemes:
- http
swagger: "2.0"
